# Generated by Django 2.1.2 on 2019-05-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
