# Generated by Django 2.1.2 on 2019-05-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topo', '0002_auto_20190515_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
