# Generated by Django 2.1.2 on 2019-05-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_arearating_cragrating_regionrating_sectorrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arearating',
            name='area',
        ),
        migrations.RemoveField(
            model_name='arearating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cragrating',
            name='crag',
        ),
        migrations.RemoveField(
            model_name='cragrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='regionrating',
            name='region',
        ),
        migrations.RemoveField(
            model_name='regionrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sectorrating',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='sectorrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='AreaRating',
        ),
        migrations.DeleteModel(
            name='CragRating',
        ),
        migrations.DeleteModel(
            name='RegionRating',
        ),
        migrations.DeleteModel(
            name='SectorRating',
        ),
    ]
