# Generated by Django 2.1.2 on 2019-05-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190521_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerating',
            name='route',
        ),
        migrations.RemoveField(
            model_name='routerating',
            name='user',
        ),
        migrations.DeleteModel(
            name='RouteRating',
        ),
    ]
