# Generated by Django 2.1.2 on 2019-05-21 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topo', '0002_auto_20190515_0257'),
        ('user', '0004_auto_20190521_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topo.Route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
